events {}

http {
    upstream users_api {
        server users-api:5001;
    }

    upstream products_api {
        server products-service:5002;
    }

    upstream orders_api {
        server orders-service:5003;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://users_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products/ {
            proxy_pass http://products_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            proxy_pass http://orders_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 'gateway ok';
            add_header Content-Type text/plain;
        }
    }
}