events {}

http {
    upstream users_api {
        server users-api:5001;
    }

    server {
        listen 80;

        location /api/users {
            rewrite ^/api/users(.*)$ /users$1 break;
            proxy_pass http://users_api;
        }

        location /health {
            return 200 "gateway ok";
        }
    }
}